# nginx-all-in-one.yaml

# --- Nginx Deployment Tanımı ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

# --- Nginx Service Tanımı ---
# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # İsteğe bağlı: Kendi NodePort'unuzu belirleyebilirsiniz. 30000-32767 arası bir değer olmalı.
                      # Belirtmezseniz Kubernetes otomatik atar.
  type: NodePort # Burayı LoadBalancer'dan NodePort'a değiştirdik
