apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort        # Cluster dışından erişim için
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container port
      nodePort: 30080   # NodePort ile erişim
