apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/engin-nvr/test-argoCD.git
    targetRevision: main
    path: apps
    directory:
      # apps/ içindeki tüm Application manifestlerini alır
      # recurse: true   

      sources:
        - path: apps/nginx-app.yaml
        - path: apps/keycloak-app.yaml # bu sekilde apps icinde calısacak dosyaları alır

      
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

