apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/engin-nvr/test-argoCD.git   # kendi repo URL'in
    targetRevision: main                                     # git branch (örn. main)
    path: manifests/keycloak                                 # chart klasörünün yolu repo içinde
    helm:
      valueFiles:
        - values.yaml                                       # chart içindeki values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
